image: docker:stable

services:
  - docker:dind

build-master:
    only: 
        - master
    tags:
        - docker
    stage: build
    script:
        - docker build -t $CI_REGISTRY_IMAGE/relay:latest -f docker/Dockerfile .
        - docker build -t $CI_REGISTRY_IMAGE/homechain:latest -f docker/homechain/Dockerfile docker/homechain
        - docker build -t $CI_REGISTRY_IMAGE/sidechain:latest -f docker/sidechain/Dockerfile docker/sidechain

build-non-master:
    except: 
        - master
    tags:
        - docker
    stage: build
    script:
        - docker build -t $CI_REGISTRY_IMAGE/relay:$CI_COMMIT_REF_NAME -f docker/Dockerfile .
        - docker build -t $CI_REGISTRY_IMAGE/homechain:$CI_COMMIT_REF_NAME -f docker/homechain/Dockerfile docker/homechain
        - docker build -t $CI_REGISTRY_IMAGE/sidechain:$CI_COMMIT_REF_NAME -f docker/sidechain/Dockerfile docker/sidechain
