[package]
name = "polyswarm-relay"
version = "0.1.0"
authors = ["PolySwarm Developers <info@polyswarm.io>"]

[build-dependencies]
glob = "0.2"
serde_json = "1.0"

[dependencies]
clap = "2.31"
config = "0.8"
ctrlc = "3.1"
env_logger = "0.5"
error-chain = "0.11"
log = "0.4"
jsonrpc-core = "8.0.1"
parking_lot = "0.5"
serde = "1.0"
serde_derive = "1.0"
tokio-core = "0.1"
web3 = { git = "https://github.com/polyswarm/rust-web3.git", branch = "relay" }
