[package]
name = "polyswarm-relay"
version = "0.1.0"
authors = ["Maxwell Koo <mjkoo90@gmail.com>", "Robert Lathrop <rl@polyswarm.io>"]

[dependencies]
web3 = { git = "https://github.com/tomusdrw/rust-web3.git" }
clap = "2.31.2"
ethabi = "5.1.1"
toml = "0.4.6"
serde = "1.0"
serde_derive = "1.0"
