[package]
name = "polyswarm-relay"
version = "0.1.0"
authors = ["PolySwarm Developers <info@polyswarm.io>"]

[build-dependencies]
glob = "0.2"
serde_json = "1.0"

[dependencies]
clap = "2.31"
config = "0.8"
ctrlc = "3.1"
ethabi = "5.1"
ethabi-contract = "5.1"
ethabi-derive = "5.1"
serde = "1.0"
serde_derive = "1.0"
web3 = { git = "https://github.com/tomusdrw/rust-web3.git" }
