[package]
name = "polyswarm-relay"
version = "0.1.0"
authors = ["Maxwell Koo <mjkoo90@gmail.com>", "Robert Lathrop <rl@polyswarm.io>"]

[dependencies]
clap = "2.31"
config = "0.8"
ctrlc = "3.1"
ethabi = "5.1"
serde = "1.0"
serde_derive = "1.0"
web3 = { git = "https://github.com/tomusdrw/rust-web3.git" }
