homechain:
    nectar_token_address: '0x9e46a38f5daabe8683e10793b06749eef7d733d1'
    bounty_registry_address: '0xe3AaC99Ab574b59dd625884c2150Ecf0aE92Bd9B'
    erc20_relay_address: ''
    chain_id: '1'
sidechain:
    nectar_token_address: ''
    bounty_registry_address: ''
    erc20_relay_address: ''
    chain_id: ''
