version: '3'
services:
    polyswarmd:
        image: "polyswarm/polyswarmd"
        depends_on:
            - geth
            - ipfs
        entrypoint:
            - polyswarmd
        environment:
            - ETH_URI=http://geth:8545
            - IPFS_URI=http://ipfs:5001
        ports:
            - "31337:31337"
    geth:
        image: "ethereum/client-go:alpine"
        ports:
            - "30303:30303"
        volumes:
            - "ethereum:/root/.ethereum"
        command: ["--fast", "--rpc", "--rpcaddr", "0.0.0.0", "--rpcvhosts", "geth", "--rpcapi", "eth,web3,personal,net"]
    ipfs:
        image: "ipfs/go-ipfs"
        environment:
            - IPFS_BIND_IP=0.0.0.0
        ports:
            - "4001:4001"
        volumes:
            - "ipfs-export:/export"
            - "ipfs-data:/data/ipfs"
volumes:
    ethereum:
    ipfs-export:
    ipfs-data:
